// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeNickname(arg1) {
  return window['go']['main']['App']['ChangeNickname'](arg1);
}

export function GetKanjiList() {
  return window['go']['main']['App']['GetKanjiList']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function Read(arg1) {
  return window['go']['main']['App']['Read'](arg1);
}

export function WriteMessage(arg1) {
  return window['go']['main']['App']['WriteMessage'](arg1);
}

export function WritePrivateMessage(arg1, arg2) {
  return window['go']['main']['App']['WritePrivateMessage'](arg1, arg2);
}
