// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeNickname(arg1:string):Promise<void>;

export function GetKanjiList():Promise<Array<string>>;

export function IsAuthenticated():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function Read(arg1:string):Promise<main.ReadResponse>;

export function WriteMessage(arg1:string):Promise<void>;

export function WritePrivateMessage(arg1:string,arg2:string):Promise<void>;
